name: Knightfall
version: '${project.version}'
main: me.verosity.knightfall.Knightfall
api-version: '1.20'
commands:
  flagremove:
    description: Spawns flag
    usage: /<command>
    permission: knightfall.admin
  kingdom:
    description: Creates a team
    usage: /kingdom create <teamName>
  giveflag:
    description: Creates a flag fweah carti carti
    usage: /giveflag
permissions:
  knightfall.admin:
    description: Run admin commands
    default: op