name: Knightfall
version: '1.0-SNAPSHOT'
main: me.verosity.knightfall.Knightfall
api-version: '1.20'
commands:
  flagtest:
    description: Spawns flag
    usage: /<command>
  flagremove:
    description: Spawns flag
    usage: /<command>